# Generated by Django 5.2.7 on 2025-11-13 06:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("proyectos", "0008_proyecto_dias_laborales_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contratista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=100, verbose_name="Apellido")),
                (
                    "numero_cedula",
                    models.CharField(
                        help_text="Formato: 0011234567890A",
                        max_length=20,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="La cédula debe tener 13 dígitos seguidos de una letra mayúscula",
                                regex="^\\d{13}[A-Z]$",
                            )
                        ],
                        verbose_name="Número de Cédula",
                    ),
                ),
                (
                    "foto_cedula",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contratistas/cedulas/",
                        verbose_name="Foto de Cédula",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        max_length=8,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="El teléfono debe tener exactamente 8 dígitos",
                                regex="^\\d{8}$",
                            )
                        ],
                        verbose_name="Teléfono",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Correo Electrónico",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(max_length=500, verbose_name="Dirección"),
                ),
                (
                    "departamento",
                    models.CharField(max_length=100, verbose_name="Departamento"),
                ),
                (
                    "municipio",
                    models.CharField(max_length=100, verbose_name="Municipio"),
                ),
                (
                    "banco",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Banco"
                    ),
                ),
                (
                    "numero_cuenta",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número de Cuenta",
                    ),
                ),
                (
                    "tipo_cuenta",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ahorro", "Cuenta de Ahorro"),
                            ("corriente", "Cuenta Corriente"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="Tipo de Cuenta",
                    ),
                ),
                (
                    "moneda_cuenta",
                    models.CharField(
                        choices=[
                            ("cordobas", "Córdobas (C$)"),
                            ("dolares", "Dólares ($)"),
                        ],
                        default="cordobas",
                        max_length=20,
                        verbose_name="Moneda de la Cuenta",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "eliminado",
                    models.BooleanField(default=False, verbose_name="Eliminado"),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("modificado_en", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contratistas_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado Por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contratista",
                "verbose_name_plural": "Contratistas",
                "db_table": "contratistas",
                "ordering": ["apellido", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="ContratoProyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Se genera automáticamente",
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(verbose_name="Descripción del Alcance"),
                ),
                (
                    "actividades",
                    models.CharField(
                        help_text="Lista de actividades separadas por coma",
                        max_length=200,
                        verbose_name="Actividades",
                    ),
                ),
                (
                    "valor_contrato",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Valor Original del Contrato",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de Inicio")),
                ("fecha_fin", models.DateField(verbose_name="Fecha de Fin")),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("planificacion", "En Planificación"),
                            ("en_proceso", "En Proceso"),
                            ("pausado", "Pausado"),
                            ("completado", "Completado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="planificacion",
                        max_length=20,
                        verbose_name="Estado del Contrato",
                    ),
                ),
                (
                    "eliminado",
                    models.BooleanField(default=False, verbose_name="Eliminado"),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("modificado_en", models.DateTimeField(auto_now=True)),
                (
                    "contratista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contratos",
                        to="contratistas.contratista",
                        verbose_name="Contratista",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contratos_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado Por",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contratos",
                        to="proyectos.proyecto",
                        verbose_name="Proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato",
                "verbose_name_plural": "Contratos",
                "db_table": "contratos_proyectos",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="PagoContratista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="PN0725-01 (PN=Pago, 07=mes, 25=año, 01=número)",
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "fecha_pago",
                    models.DateField(
                        default=django.utils.timezone.now, verbose_name="Fecha de Pago"
                    ),
                ),
                (
                    "concepto",
                    models.CharField(
                        max_length=500, verbose_name="Concepto/Descripción"
                    ),
                ),
                (
                    "monto_cordobas",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Monto en Córdobas",
                    ),
                ),
                (
                    "monto_dolares",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Monto en Dólares",
                    ),
                ),
                (
                    "tipo_cambio",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("36.6000"),
                        help_text="C$/USD al momento del pago",
                        max_digits=10,
                        verbose_name="Tipo de Cambio",
                    ),
                ),
                (
                    "forma_pago",
                    models.CharField(
                        choices=[
                            ("transferencia", "Transferencia"),
                            ("efectivo", "Efectivo"),
                            ("cheque", "Cheque (CK)"),
                        ],
                        default="transferencia",
                        max_length=20,
                        verbose_name="Forma de Pago",
                    ),
                ),
                (
                    "archivo_soporte",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="contratistas/soportes/",
                        verbose_name="Archivo Soporte",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobado_gerente", "Aprobado por Gerente"),
                            ("aprobado", "Aprobado Final"),
                            ("rechazado", "Rechazado"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_ingreso",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Ingreso"
                    ),
                ),
                (
                    "fecha_aprobacion_gerente",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Aprobación Gerente"
                    ),
                ),
                (
                    "fecha_aprobacion_contador",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Aprobación Contador"
                    ),
                ),
                (
                    "motivo_rechazo",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motivo de Rechazo"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "eliminado",
                    models.BooleanField(default=False, verbose_name="Eliminado"),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("modificado_en", models.DateTimeField(auto_now=True)),
                (
                    "aprobado_contador_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pagos_contratista_aprobados_contador",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobado por Contador",
                    ),
                ),
                (
                    "aprobado_gerente_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pagos_contratista_aprobados_gerente",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobado por Gerente",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pagos",
                        to="contratistas.contratoproyecto",
                        verbose_name="Contrato",
                    ),
                ),
                (
                    "ingresado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pagos_ingresados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ingresado Por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Pago a Contratista",
                "verbose_name_plural": "Pagos a Contratistas",
                "db_table": "pagos_contratistas",
                "ordering": ["-fecha_pago"],
            },
        ),
    ]
