# Generated by Django 5.2.7 on 2025-11-27 04:12

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("proyectos", "0008_proyecto_dias_laborales_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Contratista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=100, verbose_name="Apellido")),
                (
                    "numero_cedula",
                    models.CharField(
                        help_text="Formato: 001-DDMMYY-0000X",
                        max_length=20,
                        unique=True,
                        verbose_name="Número de Cédula",
                    ),
                ),
                (
                    "foto_cedula",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="contratistas/cedulas/",
                        verbose_name="Foto de Cédula",
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                ("direccion", models.TextField(verbose_name="Dirección")),
                (
                    "departamento",
                    models.CharField(max_length=100, verbose_name="Departamento"),
                ),
                (
                    "municipio",
                    models.CharField(max_length=100, verbose_name="Municipio"),
                ),
                (
                    "banco",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Banco"
                    ),
                ),
                (
                    "numero_cuenta",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Número de Cuenta",
                    ),
                ),
                (
                    "tipo_cuenta",
                    models.CharField(
                        blank=True,
                        choices=[("ahorro", "Ahorro"), ("corriente", "Corriente")],
                        max_length=20,
                        null=True,
                        verbose_name="Tipo de Cuenta",
                    ),
                ),
                (
                    "moneda_cuenta",
                    models.CharField(
                        choices=[("cordobas", "Córdobas"), ("dolares", "Dólares")],
                        default="cordobas",
                        max_length=20,
                        verbose_name="Moneda de la Cuenta",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "eliminado",
                    models.BooleanField(default=False, verbose_name="Eliminado"),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("modificado_en", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contratistas_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado Por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contratista",
                "verbose_name_plural": "Contratistas",
                "db_table": "contratistas",
                "ordering": ["apellido", "nombre"],
            },
        ),
        migrations.CreateModel(
            name="ContratoProyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Se genera automáticamente",
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Descripción del Contrato"
                    ),
                ),
                (
                    "actividades",
                    models.TextField(
                        help_text="Lista de actividades del contrato",
                        verbose_name="Actividades",
                    ),
                ),
                (
                    "unidad_medida",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Unidad de Medida",
                    ),
                ),
                (
                    "valor_contrato",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Valor del Contrato (C$)",
                    ),
                ),
                ("fecha_inicio", models.DateField(verbose_name="Fecha de Inicio")),
                (
                    "fecha_fin",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Fin"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("planificacion", "En Planificación"),
                            ("en_proceso", "En Proceso"),
                            ("pausado", "Pausado"),
                            ("completado", "Completado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="en_proceso",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "eliminado",
                    models.BooleanField(default=False, verbose_name="Eliminado"),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("modificado_en", models.DateTimeField(auto_now=True)),
                (
                    "contratista",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contratos",
                        to="contratistas.contratista",
                        verbose_name="Contratista",
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contratos_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado Por",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="contratos_contratistas",
                        to="proyectos.proyecto",
                        verbose_name="Proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Contrato de Proyecto",
                "verbose_name_plural": "Contratos de Proyectos",
                "db_table": "contratos_proyectos",
                "ordering": ["-fecha_inicio"],
            },
        ),
        migrations.CreateModel(
            name="AvaluoContratista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="AV0825-001 (AV=Avalúo, 08=mes, 25=año, 001=número)",
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "periodo_inicio",
                    models.DateField(
                        help_text="Fecha de inicio del período quincenal",
                        verbose_name="Inicio del Período",
                    ),
                ),
                (
                    "periodo_fin",
                    models.DateField(
                        help_text="Fecha de fin del período quincenal",
                        verbose_name="Fin del Período",
                    ),
                ),
                (
                    "porcentaje_avance",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Porcentaje acumulado de avance del contrato",
                        max_digits=5,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="% de Avance",
                    ),
                ),
                (
                    "fecha_pago",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Registro",
                    ),
                ),
                (
                    "concepto",
                    models.CharField(
                        max_length=500, verbose_name="Concepto/Descripción del Trabajo"
                    ),
                ),
                (
                    "monto_cordobas",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Monto en Córdobas",
                    ),
                ),
                (
                    "monto_dolares",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Monto en Dólares",
                    ),
                ),
                (
                    "tipo_cambio",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("36.6000"),
                        help_text="C$/USD al momento del avalúo",
                        max_digits=10,
                        verbose_name="Tipo de Cambio",
                    ),
                ),
                (
                    "forma_pago",
                    models.CharField(
                        choices=[
                            ("transferencia", "Transferencia"),
                            ("efectivo", "Efectivo"),
                            ("cheque", "Cheque (CK)"),
                        ],
                        default="transferencia",
                        max_length=20,
                        verbose_name="Forma de Pago",
                    ),
                ),
                (
                    "archivo_soporte",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="contratistas/avaluos/",
                        verbose_name="Archivo Soporte del Avalúo",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("aprobado_gerente", "Aprobado por Gerente"),
                            ("aprobado_contador", "Aprobado por Contador"),
                            ("pagado", "Pagado"),
                            ("rechazado", "Rechazado"),
                        ],
                        default="pendiente",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_ingreso",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Ingreso"
                    ),
                ),
                (
                    "fecha_aprobacion_gerente",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Aprobación Gerente"
                    ),
                ),
                (
                    "fecha_aprobacion_contador",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Aprobación Contador"
                    ),
                ),
                (
                    "motivo_rechazo",
                    models.TextField(
                        blank=True, null=True, verbose_name="Motivo de Rechazo"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "eliminado",
                    models.BooleanField(default=False, verbose_name="Eliminado"),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("modificado_en", models.DateTimeField(auto_now=True)),
                (
                    "aprobado_contador_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="avaluos_aprobados_contador",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobado por Contador",
                    ),
                ),
                (
                    "aprobado_gerente_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="avaluos_aprobados_gerente",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobado por Gerente",
                    ),
                ),
                (
                    "ingresado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="avaluos_ingresados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Ingresado Por (Supervisor)",
                    ),
                ),
                (
                    "contrato",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="avaluos",
                        to="contratistas.contratoproyecto",
                        verbose_name="Contrato",
                    ),
                ),
            ],
            options={
                "verbose_name": "Avalúo de Contratista",
                "verbose_name_plural": "Avalúos de Contratistas",
                "db_table": "pagos_contratistas",
                "ordering": ["-fecha_pago"],
            },
        ),
        migrations.CreateModel(
            name="PlanillaContratista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="PN0825-01 (PN=Planilla, 08=mes, 25=año, 01=número)",
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Ej: Planilla Proyecto Villa Fontana - Agosto 2025",
                        max_length=200,
                        verbose_name="Nombre de la Planilla",
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Inicio del Período")),
                ("periodo_fin", models.DateField(verbose_name="Fin del Período")),
                (
                    "tipo_cambio",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Tipo de cambio del BCN al momento de generar la planilla",
                        max_digits=10,
                        verbose_name="Tipo de Cambio BCN",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("aprobada_gerente", "Aprobada por Gerente"),
                            ("aprobada_contador", "Aprobada por Contador"),
                            ("pagada", "Pagada"),
                            ("anulada", "Anulada"),
                        ],
                        default="borrador",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "total_cordobas",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total en Córdobas",
                    ),
                ),
                (
                    "total_dolares",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total en Dólares",
                    ),
                ),
                (
                    "fecha_generacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Generación"
                    ),
                ),
                (
                    "fecha_aprobacion_gerente",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Aprobación Gerente"
                    ),
                ),
                (
                    "fecha_aprobacion_contador",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Aprobación Contador"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
                (
                    "eliminado",
                    models.BooleanField(default=False, verbose_name="Eliminado"),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("modificado_en", models.DateTimeField(auto_now=True)),
                (
                    "aprobada_contador_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planillas_contratistas_aprobadas_contador",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobada por Contador",
                    ),
                ),
                (
                    "aprobada_gerente_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planillas_contratistas_aprobadas_gerente",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobada por Gerente",
                    ),
                ),
                (
                    "generada_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planillas_contratistas_generadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Generada Por",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planillas_contratistas",
                        to="proyectos.proyecto",
                        verbose_name="Proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planilla de Contratistas",
                "verbose_name_plural": "Planillas de Contratistas",
                "db_table": "planillas_contratistas",
                "ordering": ["-fecha_generacion"],
            },
        ),
        migrations.CreateModel(
            name="DetallePlanillaContratista",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "contratista_nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Contratista"
                    ),
                ),
                (
                    "contratista_cedula",
                    models.CharField(max_length=20, verbose_name="Cédula"),
                ),
                (
                    "contratista_telefono",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Teléfono"
                    ),
                ),
                ("actividad", models.TextField(verbose_name="Actividad/Descripción")),
                (
                    "monto_cordobas",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Monto en Córdobas",
                    ),
                ),
                (
                    "monto_dolares",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Monto en Dólares"
                    ),
                ),
                (
                    "forma_pago",
                    models.CharField(max_length=20, verbose_name="Forma de Pago"),
                ),
                (
                    "banco",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Banco"
                    ),
                ),
                (
                    "numero_cuenta",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Cuenta"
                    ),
                ),
                (
                    "moneda_cuenta",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Moneda"
                    ),
                ),
                ("orden", models.PositiveIntegerField(default=0, verbose_name="Orden")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "avaluo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_planilla",
                        to="contratistas.avaluocontratista",
                        verbose_name="Avalúo",
                    ),
                ),
                (
                    "planilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="contratistas.planillacontratista",
                        verbose_name="Planilla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Planilla de Contratistas",
                "verbose_name_plural": "Detalles de Planillas de Contratistas",
                "db_table": "detalles_planillas_contratistas",
                "ordering": ["orden", "contratista_nombre"],
            },
        ),
    ]
