# Generated by Django 5.2.7 on 2025-10-25 06:46

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Proyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        help_text="Nombre identificador del proyecto u obra",
                        max_length=200,
                        verbose_name="Nombre del Proyecto",
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(
                        blank=True,
                        help_text="Descripción detallada del proyecto",
                        verbose_name="Descripción",
                    ),
                ),
                (
                    "ubicacion",
                    models.CharField(
                        help_text="Dirección o ubicación del proyecto",
                        max_length=300,
                        verbose_name="Ubicación",
                    ),
                ),
                (
                    "fecha_inicio",
                    models.DateField(
                        help_text="Fecha de inicio del proyecto",
                        verbose_name="Fecha de Inicio",
                    ),
                ),
                (
                    "fecha_fin_estimada",
                    models.DateField(
                        blank=True,
                        help_text="Fecha estimada de finalización",
                        null=True,
                        verbose_name="Fecha Fin Estimada",
                    ),
                ),
                (
                    "fecha_fin_real",
                    models.DateField(
                        blank=True,
                        help_text="Fecha real de finalización del proyecto",
                        null=True,
                        verbose_name="Fecha Fin Real",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("pausado", "Pausado"),
                            ("finalizado", "Finalizado"),
                            ("cancelado", "Cancelado"),
                        ],
                        default="activo",
                        help_text="Estado actual del proyecto",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "presupuesto",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Presupuesto total asignado al proyecto",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Presupuesto Total",
                    ),
                ),
                (
                    "presupuesto_gastado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Monto del presupuesto ya utilizado",
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                        verbose_name="Presupuesto Gastado",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        help_text="Supervisor responsable del proyecto",
                        limit_choices_to={"rol__in": ["administrador", "supervisor"]},
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="proyectos_supervisados",
                        to="usuarios.usuario",
                        verbose_name="Supervisor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Proyecto",
                "verbose_name_plural": "Proyectos",
                "db_table": "proyectos",
                "ordering": ["-fecha_creacion"],
                "indexes": [
                    models.Index(fields=["estado"], name="proyectos_estado_338660_idx"),
                    models.Index(
                        fields=["supervisor"], name="proyectos_supervi_ed474d_idx"
                    ),
                    models.Index(
                        fields=["fecha_inicio"], name="proyectos_fecha_i_409203_idx"
                    ),
                ],
            },
        ),
    ]
