# Generated by Django 5.2.7 on 2025-10-25 20:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proyecto",
            name="presupuesto",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="presupuesto_gastado",
        ),
        migrations.AddField(
            model_name="proyecto",
            name="anticipo",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Anticipo",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="archivo_avaluo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="proyectos/avaluos/",
                verbose_name="Avalúo",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="archivo_contrato",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="proyectos/contratos/",
                verbose_name="Contrato",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="archivo_presupuesto",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="proyectos/presupuestos/",
                verbose_name="Presupuesto",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="cantidad_unidades",
            field=models.IntegerField(
                default=0,
                help_text="Casas, oficinas, departamentos, etc.",
                verbose_name="Cantidad de Unidades",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="contratistas_asignados",
            field=models.IntegerField(default=0, verbose_name="Contratistas Asignados"),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="departamento",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Departamento"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="fecha_avaluo",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha del Avalúo"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="gasto_administrativo_real",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Gasto Administrativo Real",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="gasto_mano_obra_real",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Gasto Mano de Obra Real",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="imagen_proyecto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="proyectos/imagenes/",
                verbose_name="Imagen del Proyecto",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="municipio",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Municipio"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="personal_asignado",
            field=models.IntegerField(default=0, verbose_name="Personal Asignado"),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="porcentaje_asignacion_planilla",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="% Asignación Planilla Administrativa",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="porcentaje_avance_general",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="% Avance General",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="presupuesto_administrativo",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Presupuesto Administrativo",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="presupuesto_mano_obra",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Presupuesto Mano de Obra",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="presupuesto_total",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Presupuesto Total",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="tamano_promedio",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Tamaño Promedio (m²)",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="tamano_proyecto",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Tamaño del Proyecto (m²)",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="tipo_proyecto",
            field=models.CharField(
                choices=[
                    ("residencial", "Residencial"),
                    ("comercial", "Comercial"),
                    ("publico", "Público"),
                    ("industrial", "Industrial"),
                    ("mixto", "Mixto"),
                ],
                default="residencial",
                max_length=20,
                verbose_name="Tipo de Proyecto",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="ubicacion_coordenadas",
            field=models.CharField(
                blank=True,
                help_text="Coordenadas geográficas (lat,long)",
                max_length=100,
                verbose_name="Coordenadas",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="valor_avaluo_acumulado",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=15,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Valor Avalúo Acumulado",
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="estado",
            field=models.CharField(
                choices=[
                    ("planificacion", "En planificación"),
                    ("ejecucion", "En ejecución"),
                    ("pausado", "Pausado"),
                    ("finalizado", "Finalizado"),
                    ("cancelado", "Cancelado"),
                ],
                default="planificacion",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="fecha_fin_estimada",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha Fin Estimada"
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="fecha_fin_real",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha Fin Real"
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="fecha_inicio",
            field=models.DateField(verbose_name="Fecha de Inicio"),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="supervisor",
            field=models.ForeignKey(
                limit_choices_to={"rol__in": ["administrador", "supervisor"]},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="proyectos_supervisados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Gerente/Supervisor",
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="ubicacion",
            field=models.CharField(
                help_text="Dirección del proyecto",
                max_length=300,
                verbose_name="Dirección",
            ),
        ),
        migrations.AddIndex(
            model_name="proyecto",
            index=models.Index(
                fields=["tipo_proyecto"], name="proyectos_tipo_pr_859c94_idx"
            ),
        ),
    ]
