# Generated by Django 5.2.7 on 2025-10-25 22:38

import apps.proyectos.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0002_remove_proyecto_presupuesto_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="proyecto",
            name="proyectos_fecha_i_409203_idx",
        ),
        migrations.RemoveIndex(
            model_name="proyecto",
            name="proyectos_tipo_pr_859c94_idx",
        ),
        migrations.RenameIndex(
            model_name="proyecto",
            new_name="proyectos_p_estado_fd8518_idx",
            old_name="proyectos_estado_338660_idx",
        ),
        migrations.RenameIndex(
            model_name="proyecto",
            new_name="proyectos_p_supervi_41c0ec_idx",
            old_name="proyectos_supervi_ed474d_idx",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="fecha_fin_real",
        ),
        migrations.AddField(
            model_name="proyecto",
            name="activo",
            field=models.BooleanField(default=True, verbose_name="Activo"),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="anticipo",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=15, verbose_name="Anticipo"
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="archivo_avaluo",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.proyectos.models.avaluo_upload_path,
                verbose_name="Archivo de Avalúo",
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="archivo_contrato",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.proyectos.models.contrato_upload_path,
                verbose_name="Archivo de Contrato",
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="archivo_presupuesto",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.proyectos.models.presupuesto_upload_path,
                verbose_name="Archivo de Presupuesto",
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="cantidad_unidades",
            field=models.IntegerField(default=0, verbose_name="Cantidad de Unidades"),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="descripcion",
            field=models.TextField(blank=True, verbose_name="Descripción"),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="estado",
            field=models.CharField(
                choices=[
                    ("planificacion", "En Planificación"),
                    ("ejecucion", "En Ejecución"),
                    ("pausado", "Pausado"),
                    ("finalizado", "Finalizado"),
                    ("cancelado", "Cancelado"),
                ],
                default="planificacion",
                max_length=20,
                verbose_name="Estado del Proyecto",
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="fecha_actualizacion",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Última Actualización"
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="fecha_fin_estimada",
            field=models.DateField(
                blank=True, null=True, verbose_name="Fecha de Finalización Estimada"
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="gasto_administrativo_real",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="Gasto Real Administrativo",
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="gasto_mano_obra_real",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="Gasto Real Mano de Obra",
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="imagen_proyecto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.proyectos.models.imagen_upload_path,
                verbose_name="Imagen del Proyecto",
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="nombre",
            field=models.CharField(max_length=200, verbose_name="Nombre del Proyecto"),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="porcentaje_asignacion_planilla",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Porcentaje de Asignación de Planilla",
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="porcentaje_avance_general",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Porcentaje de Avance General",
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="presupuesto_administrativo",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="Presupuesto Administrativo",
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="presupuesto_mano_obra",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="Presupuesto Mano de Obra",
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="presupuesto_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="Presupuesto Total",
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="supervisor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="proyectos_supervisados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Supervisor/Gerente",
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="tamano_promedio",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                verbose_name="Tamaño Promedio (m²)",
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="tamano_proyecto",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=12,
                verbose_name="Tamaño del Proyecto (m²)",
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="ubicacion",
            field=models.CharField(max_length=300, verbose_name="Dirección"),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="ubicacion_coordenadas",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Coordenadas GPS"
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="valor_avaluo_acumulado",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=15,
                verbose_name="Valor Avalúo Acumulado",
            ),
        ),
        migrations.AddIndex(
            model_name="proyecto",
            index=models.Index(fields=["nombre"], name="proyectos_p_nombre_a27968_idx"),
        ),
        migrations.AlterModelTable(
            name="proyecto",
            table=None,
        ),
    ]
