# Generated by Django 5.2.7 on 2025-10-27 13:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0003_remove_proyecto_proyectos_fecha_i_409203_idx_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="creado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proyectos_creados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Creado por",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="eliminado",
            field=models.BooleanField(default=False, verbose_name="Eliminado"),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="eliminado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proyectos_eliminados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Eliminado por",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="fecha_eliminacion",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Eliminación"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="modificado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="proyectos_modificados",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Modificado por",
            ),
        ),
        migrations.AddIndex(
            model_name="proyecto",
            index=models.Index(fields=["activo"], name="proyectos_p_activo_e87e62_idx"),
        ),
        migrations.AddIndex(
            model_name="proyecto",
            index=models.Index(
                fields=["eliminado"], name="proyectos_p_elimina_1502d2_idx"
            ),
        ),
    ]
