# Generated by Django 5.2.7 on 2025-11-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0004_proyecto_creado_por_proyecto_eliminado_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="latitud",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Latitud de la ubicación del proyecto",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="longitud",
            field=models.DecimalField(
                blank=True,
                decimal_places=7,
                help_text="Longitud de la ubicación del proyecto",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="radio_geovalla",
            field=models.IntegerField(
                default=150,
                help_text="Radio permitido en metros para validación de asistencias",
            ),
        ),
    ]
