# Generated by Django 5.2.7 on 2025-11-03 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0005_proyecto_latitud_proyecto_longitud_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="hora_fin_lunes_jueves",
            field=models.TimeField(
                default="16:30", help_text="Hora de fin Lunes a Jueves (4:30 PM)"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="hora_fin_sabado",
            field=models.TimeField(
                default="12:00", help_text="Hora de fin Sábado (12:00 PM)"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="hora_fin_viernes",
            field=models.TimeField(
                default="17:00", help_text="Hora de fin Viernes (5:00 PM)"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="hora_inicio_lunes_jueves",
            field=models.TimeField(
                default="07:00", help_text="Hora de inicio Lunes a Jueves"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="hora_inicio_sabado",
            field=models.TimeField(default="07:00", help_text="Hora de inicio Sábado"),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="hora_inicio_viernes",
            field=models.TimeField(default="07:00", help_text="Hora de inicio Viernes"),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="minutos_tolerancia_entrada",
            field=models.IntegerField(
                default=15, help_text="Minutos de tolerancia para entrada"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="minutos_tolerancia_salida",
            field=models.IntegerField(
                default=10, help_text="Minutos de tolerancia para salida temprana"
            ),
        ),
    ]
