# Generated by Django 5.2.7 on 2025-11-06 06:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0006_proyecto_hora_fin_lunes_jueves_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="radio_ubicacion",
            field=models.IntegerField(
                default=100,
                help_text="Radio en metros para validar asistencias",
                validators=[
                    django.core.validators.MinValueValidator(50),
                    django.core.validators.MaxValueValidator(500),
                ],
                verbose_name="Radio de Ubicación (metros)",
            ),
        ),
    ]
