# Generated by Django 5.2.7 on 2025-11-11 17:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0007_proyecto_radio_ubicacion"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="dias_laborales",
            field=models.CharField(
                default="1,2,3,4,5",
                help_text="Días de la semana que se trabaja en este proyecto (1=Lun, 2=Mar, ..., 7=Dom)",
                max_length=50,
                verbose_name="Días Laborales",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="hora_entrada_esperada",
            field=models.TimeField(
                default=datetime.time(8, 0),
                help_text="Hora de entrada esperada para este proyecto (formato 24h)",
                verbose_name="Hora de Entrada Esperada",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="hora_salida_esperada",
            field=models.TimeField(
                default=datetime.time(17, 0),
                help_text="Hora de salida esperada para este proyecto (formato 24h)",
                verbose_name="Hora de Salida Esperada",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="horas_jornada",
            field=models.DecimalField(
                decimal_places=2,
                default=8.0,
                help_text="Cantidad de horas diarias de trabajo esperadas",
                max_digits=4,
                verbose_name="Horas por Jornada",
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="minutos_tolerancia",
            field=models.IntegerField(
                default=15,
                help_text="Minutos permitidos de retraso sin marcar como llegada tarde",
                verbose_name="Minutos de Tolerancia",
            ),
        ),
    ]
