# Generated by Django 5.2.7 on 2025-11-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contratistas", "0001_initial"),
        ("proyectos", "0008_proyecto_dias_laborales_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="contratistas",
            field=models.ManyToManyField(
                blank=True,
                related_name="proyectos_asignados",
                to="contratistas.contratista",
                verbose_name="Contratistas Asignados",
            ),
        ),
    ]
