# Generated by Django 5.2.7 on 2026-01-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0009_proyecto_contratistas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="proyecto",
            name="hora_fin_lunes_jueves",
        ),
        migrations.RemoveField(
            model_name="proyecto",
            name="hora_inicio_lunes_jueves",
        ),
        migrations.AddField(
            model_name="proyecto",
            name="hora_fin_domingo",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hora de fin Domingo (formato 12h, opcional)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="hora_fin_jueves",
            field=models.CharField(
                default="05:00 PM",
                help_text="Hora de fin Jueves (formato 12h)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="hora_fin_lunes",
            field=models.CharField(
                default="05:00 PM",
                help_text="Hora de fin Lunes (formato 12h: 05:00 PM)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="hora_fin_martes",
            field=models.CharField(
                default="05:00 PM",
                help_text="Hora de fin Martes (formato 12h)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="hora_fin_miercoles",
            field=models.CharField(
                default="05:00 PM",
                help_text="Hora de fin Miércoles (formato 12h)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="hora_inicio_domingo",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hora de inicio Domingo (formato 12h, opcional)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="hora_inicio_jueves",
            field=models.CharField(
                default="08:00 AM",
                help_text="Hora de inicio Jueves (formato 12h)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="hora_inicio_lunes",
            field=models.CharField(
                default="08:00 AM",
                help_text="Hora de inicio Lunes (formato 12h: 08:00 AM)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="hora_inicio_martes",
            field=models.CharField(
                default="08:00 AM",
                help_text="Hora de inicio Martes (formato 12h)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="hora_inicio_miercoles",
            field=models.CharField(
                default="08:00 AM",
                help_text="Hora de inicio Miércoles (formato 12h)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="hora_fin_sabado",
            field=models.CharField(
                default="12:00 PM",
                help_text="Hora de fin Sábado (formato 12h)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="hora_fin_viernes",
            field=models.CharField(
                default="02:00 PM",
                help_text="Hora de fin Viernes (formato 12h)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="hora_inicio_sabado",
            field=models.CharField(
                default="08:00 AM",
                help_text="Hora de inicio Sábado (formato 12h)",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="proyecto",
            name="hora_inicio_viernes",
            field=models.CharField(
                default="08:00 AM",
                help_text="Hora de inicio Viernes (formato 12h)",
                max_length=10,
            ),
        ),
    ]
