# Generated by Django 5.2.7 on 2026-02-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0010_remove_proyecto_hora_fin_lunes_jueves_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="descanso_domingo",
            field=models.CharField(
                blank=True,
                default="0:00",
                help_text="Tiempo de descanso/comida Domingo",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="descanso_jueves",
            field=models.CharField(
                default="1:00",
                help_text="Tiempo de descanso/comida Jueves",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="descanso_lunes",
            field=models.CharField(
                default="1:00",
                help_text="Tiempo de descanso/comida Lunes (formato H:MM, ej: 1:00, 0:30, 1:30)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="descanso_martes",
            field=models.CharField(
                default="1:00",
                help_text="Tiempo de descanso/comida Martes",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="descanso_miercoles",
            field=models.CharField(
                default="1:00",
                help_text="Tiempo de descanso/comida Miércoles",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="descanso_sabado",
            field=models.CharField(
                default="0:00",
                help_text="Tiempo de descanso/comida Sábado",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="descanso_viernes",
            field=models.CharField(
                default="1:00",
                help_text="Tiempo de descanso/comida Viernes",
                max_length=10,
            ),
        ),
    ]
