# Generated by Django 5.2.7 on 2026-02-17 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "proyectos",
            "0011_proyecto_descanso_domingo_proyecto_descanso_jueves_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UsuarioProyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_asignacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Asignación"
                    ),
                ),
                ("activo", models.BooleanField(default=True)),
                (
                    "asignado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asignaciones_realizadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Asignado por",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usuarios_asignados",
                        to="proyectos.proyecto",
                        verbose_name="Proyecto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proyectos_asignados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asignación Usuario-Proyecto",
                "db_table": "usuario_proyecto",
                "unique_together": {("usuario", "proyecto")},
            },
        ),
    ]
