# Generated by Django 5.2.7 on 2026-02-27 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0012_usuarioproyecto"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="is_administrativo",
            field=models.BooleanField(
                default=False,
                help_text="Proyecto virtual para personal administrativo (sueldo fijo, no por horas)",
                verbose_name="Proyecto Administrativo",
            ),
        ),
    ]
