# Generated by Django 5.2.7 on 2026-03-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("proyectos", "0013_proyecto_is_administrativo"),
    ]

    operations = [
        migrations.AddField(
            model_name="proyecto",
            name="guarda_hora_fin_domingo",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hora salida guarda Lunes AM (opcional)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="guarda_hora_fin_jueves",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hora salida guarda Viernes AM",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="guarda_hora_fin_lunes",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hora salida guarda Martes AM (ej: 07:00 AM)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="guarda_hora_fin_martes",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hora salida guarda Miércoles AM",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="guarda_hora_fin_miercoles",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hora salida guarda Jueves AM",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="guarda_hora_fin_sabado",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hora salida guarda Lunes AM",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="guarda_hora_fin_viernes",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hora salida guarda Sábado AM",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="guarda_hora_inicio_domingo",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hora entrada guarda Domingo (opcional)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="guarda_hora_inicio_jueves",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hora entrada guarda Jueves",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="guarda_hora_inicio_lunes",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hora entrada guarda Lunes (ej: 04:30 PM)",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="guarda_hora_inicio_martes",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hora entrada guarda Martes",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="guarda_hora_inicio_miercoles",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hora entrada guarda Miércoles",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="guarda_hora_inicio_sabado",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hora entrada guarda Sábado",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="guarda_hora_inicio_viernes",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Hora entrada guarda Viernes",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="guarda_turnos_domingo",
            field=models.IntegerField(
                default=0, help_text="Cantidad de turnos Domingo"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="guarda_turnos_jueves",
            field=models.IntegerField(
                default=1, help_text="Cantidad de turnos que cuenta este día"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="guarda_turnos_lunes",
            field=models.IntegerField(
                default=1, help_text="Cantidad de turnos que cuenta este día"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="guarda_turnos_martes",
            field=models.IntegerField(
                default=1, help_text="Cantidad de turnos que cuenta este día"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="guarda_turnos_miercoles",
            field=models.IntegerField(
                default=1, help_text="Cantidad de turnos que cuenta este día"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="guarda_turnos_sabado",
            field=models.IntegerField(
                default=2, help_text="Cantidad de turnos que cuenta (sábado = 2)"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="guarda_turnos_viernes",
            field=models.IntegerField(
                default=1, help_text="Cantidad de turnos que cuenta este día"
            ),
        ),
        migrations.AddField(
            model_name="proyecto",
            name="tiene_guardas",
            field=models.BooleanField(
                default=False,
                help_text="Activar para configurar horario de guardas",
                verbose_name="Tiene Guardas de Seguridad",
            ),
        ),
    ]
