# Generated by Django 5.2.7 on 2025-11-14 03:08

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfiguracionSistema",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_cambio_actual",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("36.6000"),
                        help_text="Tipo de cambio oficial para conversión de córdobas a dólares",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="Tipo de Cambio Actual (C$/USD)",
                    ),
                ),
                (
                    "actualizado_en",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
                (
                    "nombre_empresa",
                    models.CharField(
                        default="Quadycons",
                        max_length=200,
                        verbose_name="Nombre de la Empresa",
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración del Sistema",
                "verbose_name_plural": "Configuración del Sistema",
                "db_table": "configuracion_sistema",
            },
        ),
        migrations.CreateModel(
            name="HistorialTipoCambio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_cambio",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                        verbose_name="Tipo de Cambio",
                    ),
                ),
                (
                    "fecha_cambio",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha del Cambio",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, null=True, verbose_name="Observaciones"
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Tipo de Cambio",
                "verbose_name_plural": "Historial de Tipos de Cambio",
                "db_table": "historial_tipo_cambio",
                "ordering": ["-fecha_cambio"],
            },
        ),
    ]
