# Generated by Django 5.2.7 on 2025-11-12 22:37

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("proyectos", "0008_proyecto_dias_laborales_and_more"),
        ("trabajadores", "0002_trabajador_codigo_qr"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Planilla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Se genera automáticamente",
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                (
                    "periodo_inicio",
                    models.DateField(
                        help_text="Se sugiere iniciar en jueves",
                        verbose_name="Período Inicio",
                    ),
                ),
                (
                    "periodo_fin",
                    models.DateField(
                        help_text="Se sugiere terminar en martes",
                        verbose_name="Período Fin",
                    ),
                ),
                (
                    "tipo_cambio",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("36.6000"),
                        help_text="C$/USD al momento de generar",
                        max_digits=10,
                        verbose_name="Tipo de Cambio",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("aprobada_gerente", "Aprobada por Gerente"),
                            ("aprobada_final", "Aprobada Final"),
                            ("pagada", "Pagada"),
                            ("cancelada", "Cancelada"),
                        ],
                        default="borrador",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "fecha_generacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Generación"
                    ),
                ),
                (
                    "fecha_aprobacion_gerente",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Aprobación Gerente"
                    ),
                ),
                (
                    "fecha_aprobacion_contador",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Aprobación Contador"
                    ),
                ),
                (
                    "fecha_aprobacion_final",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha Aprobación Final"
                    ),
                ),
                (
                    "fecha_pago",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Pago"
                    ),
                ),
                (
                    "total_cordobas",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total Córdobas",
                    ),
                ),
                (
                    "total_dolares",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total Dólares",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "eliminado",
                    models.BooleanField(default=False, verbose_name="Eliminado"),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("modificado_en", models.DateTimeField(auto_now=True)),
                (
                    "aprobada_contador_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planillas_aprobadas_contador",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobada Contador Por",
                    ),
                ),
                (
                    "aprobada_final_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planillas_aprobadas_final",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobada Final Por",
                    ),
                ),
                (
                    "aprobada_gerente_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planillas_aprobadas_gerente",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobada Gerente Por",
                    ),
                ),
                (
                    "generada_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planillas_generadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Generada Por",
                    ),
                ),
                (
                    "pagada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="planillas_pagadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Pagada Por",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planillas",
                        to="proyectos.proyecto",
                        verbose_name="Proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Planilla",
                "verbose_name_plural": "Planillas",
                "db_table": "planillas",
                "ordering": ["-fecha_generacion"],
                "unique_together": {("proyecto", "periodo_inicio", "periodo_fin")},
            },
        ),
        migrations.CreateModel(
            name="PlanillaReembolso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_item", models.IntegerField(verbose_name="N°")),
                (
                    "concepto",
                    models.CharField(
                        help_text="Ej: INSS, INATEC, Horas Extra, PLOTER, etc.",
                        max_length=500,
                        verbose_name="Concepto",
                    ),
                ),
                (
                    "monto_cordobas",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Monto Córdobas",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("modificado_en", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reembolsos_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado Por",
                    ),
                ),
                (
                    "planilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reembolsos",
                        to="planillas.planilla",
                        verbose_name="Planilla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reembolso y Otros Gastos",
                "verbose_name_plural": "Reembolsos y Otros Gastos",
                "db_table": "planillas_reembolsos",
                "ordering": ["numero_item"],
            },
        ),
        migrations.CreateModel(
            name="TipoCambio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        default=django.utils.timezone.now,
                        unique=True,
                        verbose_name="Fecha",
                    ),
                ),
                (
                    "valor",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("36.6000"),
                        help_text="Tipo de cambio oficial BCN",
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                        verbose_name="Valor (C$/USD)",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Tipo de cambio actualmente en uso",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "fecha_modificacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Modificación"
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modificado Por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tipo de Cambio",
                "verbose_name_plural": "Tipos de Cambio",
                "db_table": "tipos_cambio",
                "ordering": ["-fecha"],
            },
        ),
        migrations.CreateModel(
            name="DiaFeriado",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(db_index=True, verbose_name="Fecha")),
                (
                    "descripcion",
                    models.CharField(max_length=200, verbose_name="Descripción"),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("nacional", "Nacional"),
                            ("proyecto", "Específico de Proyecto"),
                        ],
                        default="nacional",
                        max_length=20,
                        verbose_name="Tipo",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado Por",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        blank=True,
                        help_text="Solo si es feriado específico de proyecto",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dias_feriados",
                        to="proyectos.proyecto",
                        verbose_name="Proyecto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Día Feriado",
                "verbose_name_plural": "Días Feriados",
                "db_table": "dias_feriados",
                "ordering": ["fecha"],
                "unique_together": {("fecha", "tipo", "proyecto")},
            },
        ),
        migrations.CreateModel(
            name="DetallePlanilla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("administrativo", "Administrativo de Proyecto"),
                            ("oficiales", "Oficiales"),
                            ("ayudantes", "Ayudantes"),
                            ("subcontratista", "Sub-Contratista"),
                        ],
                        default="oficiales",
                        max_length=20,
                        verbose_name="Área",
                    ),
                ),
                ("cargo", models.CharField(max_length=100, verbose_name="Cargo")),
                (
                    "dias_laborados",
                    models.IntegerField(
                        default=0,
                        help_text="Días efectivamente trabajados (máx 12 en catorcena)",
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Días Laborados",
                    ),
                ),
                (
                    "horas_normales",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=6,
                        verbose_name="Horas Normales",
                    ),
                ),
                (
                    "horas_extras",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=6,
                        verbose_name="Horas Extras",
                    ),
                ),
                (
                    "horas_dominicales",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Horas trabajadas en domingo",
                        max_digits=6,
                        verbose_name="Horas Dominicales",
                    ),
                ),
                (
                    "dias_feriados",
                    models.IntegerField(
                        default=0,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Días Feriados Trabajados",
                    ),
                ),
                (
                    "salario_dia_base",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Salario Día Base",
                    ),
                ),
                (
                    "valor_septimo_dia",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Calculado: salario_dia_base / 6",
                        max_digits=10,
                        verbose_name="Valor 7mo Día",
                    ),
                ),
                (
                    "salario_diario_con_septimo",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="salario_dia_base + valor_septimo_dia",
                        max_digits=10,
                        verbose_name="Salario Diario + 7mo",
                    ),
                ),
                (
                    "valor_hora_base",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Calculado: salario_dia_base / 12",
                        max_digits=10,
                        verbose_name="Valor Hora Base",
                    ),
                ),
                (
                    "salario_devengado",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="dias_laborados × salario_diario_con_septimo",
                        max_digits=10,
                        verbose_name="Salario Devengado",
                    ),
                ),
                (
                    "salario_horas_extras",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="(valor_hora_base × 2) × horas_extras",
                        max_digits=10,
                        verbose_name="Salario Horas Extras",
                    ),
                ),
                (
                    "salario_horas_dominicales",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="(valor_hora_base × 2) × horas_dominicales",
                        max_digits=10,
                        verbose_name="Salario Horas Dominicales",
                    ),
                ),
                (
                    "salario_dias_feriados",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Digitado por residente, autorizado por gerente",
                        max_digits=10,
                        verbose_name="Salario Días Feriados",
                    ),
                ),
                (
                    "combustible",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Digitado por residente, autorizado por gerente",
                        max_digits=10,
                        verbose_name="Combustible",
                    ),
                ),
                (
                    "bonos",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        help_text="Digitado por residente, autorizado por gerente",
                        max_digits=10,
                        verbose_name="Bonos",
                    ),
                ),
                (
                    "otros_gastos",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Otros Gastos",
                    ),
                ),
                (
                    "otros_gastos_descripcion",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="Descripción Otros Gastos",
                    ),
                ),
                (
                    "ingreso_total",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=10,
                        verbose_name="Ingreso Total",
                    ),
                ),
                (
                    "fecha_edicion",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Fecha de Edición"
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "editado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Editado Por",
                    ),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="detalles_planilla",
                        to="trabajadores.trabajador",
                        verbose_name="Trabajador",
                    ),
                ),
                (
                    "planilla",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="planillas.planilla",
                        verbose_name="Planilla",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Planilla",
                "verbose_name_plural": "Detalles de Planilla",
                "db_table": "detalles_planilla",
                "ordering": ["area", "trabajador__apellido", "trabajador__nombre"],
                "unique_together": {("planilla", "trabajador")},
            },
        ),
    ]
