# Generated by Django 5.2.7 on 2025-11-13 04:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planillas", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalleplanilla",
            name="deducciones",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Deducciones varias (ej. adelantos)",
                max_digits=10,
                verbose_name="Deducciones",
            ),
        ),
    ]
