# Generated by Django 5.2.7 on 2025-11-13 04:54

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planillas", "0002_detalleplanilla_deducciones"),
    ]

    operations = [
        migrations.AddField(
            model_name="detalleplanilla",
            name="inatec",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Lo paga la empresa",
                max_digits=10,
                verbose_name="INATEC (2%)",
            ),
        ),
        migrations.AddField(
            model_name="detalleplanilla",
            name="inss_laboral",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Se descuenta al trabajador",
                max_digits=10,
                verbose_name="INSS Laboral (6.25%)",
            ),
        ),
        migrations.AddField(
            model_name="detalleplanilla",
            name="inss_patronal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Lo paga la empresa",
                max_digits=10,
                verbose_name="INSS Patronal (19%)",
            ),
        ),
        migrations.AddField(
            model_name="planilla",
            name="total_inatec",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Total INATEC",
            ),
        ),
        migrations.AddField(
            model_name="planilla",
            name="total_inss_laboral",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Total INSS Laboral",
            ),
        ),
        migrations.AddField(
            model_name="planilla",
            name="total_inss_patronal",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                verbose_name="Total INSS Patronal",
            ),
        ),
    ]
