# Generated by Django 5.2.7 on 2026-02-27 06:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "planillas",
            "0003_detalleplanilla_inatec_detalleplanilla_inss_laboral_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="detalleplanilla",
            name="aguinaldo",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="(2.5/30) × Salario Base",
                max_digits=10,
                verbose_name="Aguinaldo",
            ),
        ),
        migrations.AddField(
            model_name="detalleplanilla",
            name="antiguedad",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="(2.5/30) × Salario Base",
                max_digits=10,
                verbose_name="Antigüedad",
            ),
        ),
        migrations.AddField(
            model_name="detalleplanilla",
            name="horas_feriado",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Horas trabajadas en días feriados",
                max_digits=6,
                verbose_name="Horas en Día Feriado",
            ),
        ),
        migrations.AddField(
            model_name="detalleplanilla",
            name="ingreso_dia_feriado",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="(Días Feriados × Día Base) + (Horas Feriado × Tarifa HE)",
                max_digits=10,
                verbose_name="Ingreso Día Feriado",
            ),
        ),
        migrations.AddField(
            model_name="detalleplanilla",
            name="otros_ingresos",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                verbose_name="Otros Ingresos",
            ),
        ),
        migrations.AddField(
            model_name="detalleplanilla",
            name="salario_prestacionado",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Salario Base + Vacaciones + Aguinaldo + Antigüedad",
                max_digits=10,
                verbose_name="Salario Prestacionado",
            ),
        ),
        migrations.AddField(
            model_name="detalleplanilla",
            name="vacaciones",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="(2.5/30) × Salario Base",
                max_digits=10,
                verbose_name="Vacaciones",
            ),
        ),
    ]
