# Generated by Django 5.2.7 on 2026-03-28 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "planillas",
            "0004_detalleplanilla_aguinaldo_detalleplanilla_antiguedad_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="detalleplanilla",
            name="area",
            field=models.CharField(
                choices=[
                    ("administrativo", "Administrativo de Proyecto"),
                    ("oficiales", "Oficiales"),
                    ("ayudantes", "Ayudantes"),
                    ("guardas", "Guardas de Seguridad"),
                    ("subcontratista", "Sub-Contratista"),
                ],
                default="oficiales",
                max_length=20,
                verbose_name="Área",
            ),
        ),
    ]
