# Generated by Django 5.2.7 on 2025-10-27 20:43

import apps.trabajadores.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("proyectos", "0004_proyecto_creado_por_proyecto_eliminado_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trabajador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=100, verbose_name="Apellido")),
                (
                    "numero_cedula",
                    models.CharField(
                        help_text="Documento de identidad único",
                        max_length=50,
                        unique=True,
                        verbose_name="Número de Cédula",
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Nacimiento"
                    ),
                ),
                (
                    "sexo",
                    models.CharField(
                        choices=[
                            ("masculino", "Masculino"),
                            ("femenino", "Femenino"),
                            ("otro", "Otro"),
                        ],
                        default="masculino",
                        max_length=20,
                        verbose_name="Sexo",
                    ),
                ),
                (
                    "tipo_sangre",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A+", "A+"),
                            ("A-", "A-"),
                            ("B+", "B+"),
                            ("B-", "B-"),
                            ("AB+", "AB+"),
                            ("AB-", "AB-"),
                            ("O+", "O+"),
                            ("O-", "O-"),
                        ],
                        max_length=5,
                        verbose_name="Tipo de Sangre",
                    ),
                ),
                (
                    "departamento",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Departamento"
                    ),
                ),
                (
                    "municipio",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Municipio"
                    ),
                ),
                ("direccion", models.TextField(blank=True, verbose_name="Dirección")),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Correo Electrónico",
                    ),
                ),
                (
                    "contacto_emergencia",
                    models.CharField(
                        blank=True,
                        help_text="Nombre y teléfono de contacto de emergencia",
                        max_length=200,
                        verbose_name="Contacto de Emergencia",
                    ),
                ),
                (
                    "puesto_laboral",
                    models.CharField(max_length=100, verbose_name="Puesto Laboral"),
                ),
                (
                    "area_cargo",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Área/Cargo"
                    ),
                ),
                (
                    "fecha_ingreso",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Ingreso",
                    ),
                ),
                (
                    "fecha_salida",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Salida"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("activo", "Activo"),
                            ("inactivo", "Inactivo"),
                            ("suspendido", "Suspendido"),
                            ("retirado", "Retirado"),
                        ],
                        default="activo",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "salario_normal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tarifa por hora normal",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Salario Normal (por hora)",
                    ),
                ),
                (
                    "tarifa_hora_extra",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tarifa por día o por hora extra",
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Tarifa Hora Extra",
                    ),
                ),
                (
                    "salario_festivo",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Salario Festivo",
                    ),
                ),
                (
                    "salario_nocturno",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Salario Nocturno",
                    ),
                ),
                (
                    "numero_seguro_social",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Número de Seguro Social",
                    ),
                ),
                (
                    "asegurado",
                    models.BooleanField(default=False, verbose_name="Asegurado"),
                ),
                (
                    "record_policia",
                    models.BooleanField(
                        default=False, verbose_name="Record de Policía Entregado"
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.trabajadores.models.trabajador_foto_path,
                        verbose_name="Foto del Trabajador",
                    ),
                ),
                (
                    "foto_cedula_frontal",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.trabajadores.models.trabajador_cedula_frontal_path,
                        verbose_name="Foto de Cédula (Frontal)",
                    ),
                ),
                (
                    "foto_cedula_posterior",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.trabajadores.models.trabajador_cedula_posterior_path,
                        verbose_name="Foto de Cédula (Posterior)",
                    ),
                ),
                (
                    "foto_cedula",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.trabajadores.models.trabajador_cedula_frontal_path,
                        verbose_name="Foto de Cédula (Única)",
                    ),
                ),
                (
                    "record_policia_doc",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.trabajadores.models.trabajador_record_policia_path,
                        verbose_name="Record de Policía (Documento)",
                    ),
                ),
                (
                    "archivo_contrato",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.trabajadores.models.trabajador_contrato_path,
                        verbose_name="Archivo de Contrato",
                    ),
                ),
                (
                    "notas",
                    models.TextField(
                        blank=True,
                        help_text="Observaciones adicionales sobre el trabajador",
                        verbose_name="Notas",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "modificado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado en"),
                ),
                (
                    "eliminado",
                    models.BooleanField(default=False, verbose_name="Eliminado"),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trabajadores_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "modificado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trabajadores_modificados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modificado por",
                    ),
                ),
                (
                    "proyecto_asignado",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trabajadores",
                        to="proyectos.proyecto",
                        verbose_name="Proyecto Asignado",
                    ),
                ),
            ],
            options={
                "verbose_name": "Trabajador",
                "verbose_name_plural": "Trabajadores",
                "db_table": "trabajadores",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="HistorialProyecto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha_asignacion",
                    models.DateField(
                        default=django.utils.timezone.now,
                        verbose_name="Fecha de Asignación",
                    ),
                ),
                (
                    "fecha_salida",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Salida"
                    ),
                ),
                (
                    "motivo",
                    models.TextField(
                        blank=True,
                        help_text="Motivo de la asignación o traslado",
                        verbose_name="Motivo",
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_trabajadores",
                        to="proyectos.proyecto",
                        verbose_name="Proyecto",
                    ),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historial_proyectos",
                        to="trabajadores.trabajador",
                        verbose_name="Trabajador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial de Proyecto",
                "verbose_name_plural": "Historiales de Proyectos",
                "db_table": "trabajadores_historial_proyectos",
                "ordering": ["-fecha_asignacion"],
            },
        ),
        migrations.CreateModel(
            name="DocumentoTrabajador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("contrato", "Contrato"),
                            ("certificado", "Certificado"),
                            ("titulo", "Título"),
                            ("licencia", "Licencia"),
                            ("otro", "Otro"),
                        ],
                        default="otro",
                        max_length=20,
                        verbose_name="Tipo de Documento",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(
                        max_length=200, verbose_name="Nombre del Documento"
                    ),
                ),
                (
                    "archivo",
                    models.FileField(
                        upload_to="trabajadores/documentos/", verbose_name="Archivo"
                    ),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "fecha_emision",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Emisión"
                    ),
                ),
                (
                    "fecha_vencimiento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Vencimiento"
                    ),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documentos_adicionales",
                        to="trabajadores.trabajador",
                        verbose_name="Trabajador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento del Trabajador",
                "verbose_name_plural": "Documentos de Trabajadores",
                "db_table": "trabajadores_documentos",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.AddIndex(
            model_name="trabajador",
            index=models.Index(
                fields=["numero_cedula"], name="trabajadore_numero__0b56fc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trabajador",
            index=models.Index(fields=["estado"], name="trabajadore_estado_1a4a8c_idx"),
        ),
        migrations.AddIndex(
            model_name="trabajador",
            index=models.Index(
                fields=["proyecto_asignado"], name="trabajadore_proyect_e2ffe0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="trabajador",
            index=models.Index(
                fields=["eliminado"], name="trabajadore_elimina_2acd86_idx"
            ),
        ),
    ]
