# Generated by Django 5.2.7 on 2025-10-29 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trabajadores", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trabajador",
            name="codigo_qr",
            field=models.ImageField(
                blank=True,
                help_text="Código QR generado automáticamente para registro de asistencias",
                null=True,
                upload_to="trabajadores/qr/",
                verbose_name="Código QR",
            ),
        ),
    ]
