# Generated by Django 5.2.7 on 2026-02-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trabajadores", "0002_trabajador_codigo_qr"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trabajador",
            name="numero_cedula",
            field=models.CharField(
                blank=True,
                help_text="Documento de identidad único",
                max_length=50,
                null=True,
                unique=True,
                verbose_name="Número de Cédula",
            ),
        ),
    ]
