# Generated by Django 5.2.7 on 2026-03-16 01:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trabajadores", "0003_alter_trabajador_numero_cedula"),
    ]

    operations = [
        migrations.AddField(
            model_name="trabajador",
            name="bonos",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Bono que se incluye automáticamente en cada planilla",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Bonos",
            ),
        ),
    ]
