# Generated by Django 5.2.7 on 2026-03-28 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trabajadores", "0004_trabajador_bonos"),
    ]

    operations = [
        migrations.AddField(
            model_name="trabajador",
            name="tipo_pago",
            field=models.CharField(
                choices=[("por_hora", "Por Hora"), ("por_turno", "Por Turno")],
                default="por_hora",
                help_text="Por hora para trabajadores normales, Por turno para guardas",
                max_length=20,
                verbose_name="Tipo de Pago",
            ),
        ),
        migrations.AlterField(
            model_name="trabajador",
            name="salario_normal",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Tarifa por hora o valor por turno según tipo de pago",
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="Salario Normal",
            ),
        ),
    ]
