# Generated by Django 5.2.7 on 2025-10-29 16:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("proyectos", "0004_proyecto_creado_por_proyecto_eliminado_and_more"),
        ("trabajadores", "0002_trabajador_codigo_qr"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Asistencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fecha",
                    models.DateField(
                        db_index=True,
                        default=django.utils.timezone.now,
                        verbose_name="Fecha",
                    ),
                ),
                (
                    "hora_entrada",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de Entrada"
                    ),
                ),
                (
                    "hora_salida",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de Salida"
                    ),
                ),
                (
                    "horas_normales",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Horas Normales",
                    ),
                ),
                (
                    "horas_extras",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Horas Extras",
                    ),
                ),
                (
                    "horas_totales",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Horas Totales",
                    ),
                ),
                (
                    "puesto_laboral",
                    models.CharField(
                        blank=True,
                        help_text="Snapshot del cargo al momento del registro",
                        max_length=100,
                        verbose_name="Puesto Laboral",
                    ),
                ),
                (
                    "salario_dia",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Salario correspondiente al día trabajado",
                        max_digits=10,
                        verbose_name="Salario del Día",
                    ),
                ),
                (
                    "tarifa_hora_extra",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Tarifa por hora extra",
                        max_digits=10,
                        verbose_name="Tarifa Hora Extra",
                    ),
                ),
                (
                    "latitud_entrada",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Latitud Entrada",
                    ),
                ),
                (
                    "longitud_entrada",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Longitud Entrada",
                    ),
                ),
                (
                    "distancia_entrada",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Distancia al proyecto al momento del check-in",
                        max_digits=10,
                        null=True,
                        verbose_name="Distancia Entrada (metros)",
                    ),
                ),
                (
                    "ubicacion_entrada_valida",
                    models.BooleanField(
                        default=True, verbose_name="Ubicación Entrada Válida"
                    ),
                ),
                (
                    "latitud_salida",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Latitud Salida",
                    ),
                ),
                (
                    "longitud_salida",
                    models.DecimalField(
                        blank=True,
                        decimal_places=7,
                        max_digits=10,
                        null=True,
                        verbose_name="Longitud Salida",
                    ),
                ),
                (
                    "distancia_salida",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Distancia Salida (metros)",
                    ),
                ),
                (
                    "ubicacion_salida_valida",
                    models.BooleanField(
                        default=True, verbose_name="Ubicación Salida Válida"
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("pendiente", "Pendiente"),
                            ("abierto", "Abierto"),
                            ("cerrado", "Cerrado"),
                            ("sincronizado", "Sincronizado"),
                        ],
                        default="abierto",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "llego_tarde",
                    models.BooleanField(
                        default=False,
                        help_text="Si llegó después de la hora establecida",
                        verbose_name="Llegó Tarde",
                    ),
                ),
                (
                    "salio_temprano",
                    models.BooleanField(
                        default=False,
                        help_text="Si salió antes de la hora establecida",
                        verbose_name="Salió Temprano",
                    ),
                ),
                (
                    "dispositivo_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="ID del Dispositivo"
                    ),
                ),
                (
                    "metodo_identificacion",
                    models.CharField(
                        choices=[
                            ("qr", "QR Generado"),
                            ("cedula", "Cédula Física"),
                            ("manual", "Manual"),
                        ],
                        default="qr",
                        max_length=20,
                        verbose_name="Método de Identificación",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "modificado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado en"),
                ),
                (
                    "sincronizado_en",
                    models.DateTimeField(
                        blank=True,
                        help_text="Momento en que se sincronizó desde la app móvil",
                        null=True,
                        verbose_name="Sincronizado en",
                    ),
                ),
                (
                    "editado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asistencias_editadas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Editado Por",
                    ),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencias",
                        to="proyectos.proyecto",
                        verbose_name="Proyecto",
                    ),
                ),
                (
                    "registrado_por",
                    models.ForeignKey(
                        blank=True,
                        help_text="Usuario que registró la asistencia (app móvil o web)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="asistencias_registradas",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Registrado Por",
                    ),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="asistencias",
                        to="trabajadores.trabajador",
                        verbose_name="Trabajador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Asistencia",
                "verbose_name_plural": "Asistencias",
                "db_table": "asistencias",
                "ordering": ["-fecha", "-hora_entrada"],
                "indexes": [
                    models.Index(
                        fields=["trabajador", "fecha"],
                        name="asistencias_trabaja_22d0c7_idx",
                    ),
                    models.Index(
                        fields=["proyecto", "fecha"],
                        name="asistencias_proyect_082f7c_idx",
                    ),
                    models.Index(
                        fields=["fecha", "estado"], name="asistencias_fecha_3831c0_idx"
                    ),
                    models.Index(
                        fields=["estado"], name="asistencias_estado_a73000_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ResumenDiario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(db_index=True, verbose_name="Fecha")),
                ("asistio", models.BooleanField(default=True, verbose_name="Asistió")),
                (
                    "hora_entrada",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de Entrada"
                    ),
                ),
                (
                    "hora_salida",
                    models.TimeField(
                        blank=True, null=True, verbose_name="Hora de Salida"
                    ),
                ),
                (
                    "horas_normales",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Horas Normales",
                    ),
                ),
                (
                    "horas_extras",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Horas Extras",
                    ),
                ),
                (
                    "horas_totales",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=5,
                        verbose_name="Horas Totales",
                    ),
                ),
                (
                    "llego_tarde",
                    models.BooleanField(default=False, verbose_name="Llegó Tarde"),
                ),
                (
                    "salio_temprano",
                    models.BooleanField(default=False, verbose_name="Salió Temprano"),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "creado_en",
                    models.DateTimeField(auto_now_add=True, verbose_name="Creado en"),
                ),
                (
                    "modificado_en",
                    models.DateTimeField(auto_now=True, verbose_name="Modificado en"),
                ),
                (
                    "proyecto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumenes_diarios",
                        to="proyectos.proyecto",
                        verbose_name="Proyecto",
                    ),
                ),
                (
                    "trabajador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resumenes_diarios",
                        to="trabajadores.trabajador",
                        verbose_name="Trabajador",
                    ),
                ),
            ],
            options={
                "verbose_name": "Resumen Diario",
                "verbose_name_plural": "Resúmenes Diarios",
                "db_table": "asistencias_resumen_diario",
                "ordering": ["-fecha"],
                "indexes": [
                    models.Index(
                        fields=["fecha", "proyecto"],
                        name="asistencias_fecha_d69d91_idx",
                    ),
                    models.Index(
                        fields=["trabajador", "fecha"],
                        name="asistencias_trabaja_4fc997_idx",
                    ),
                ],
                "unique_together": {("trabajador", "fecha")},
            },
        ),
    ]
