# Generated by Django 5.2.7 on 2025-10-30 03:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistencias", "0001_initial"),
        ("proyectos", "0004_proyecto_creado_por_proyecto_eliminado_and_more"),
        ("trabajadores", "0002_trabajador_codigo_qr"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="asistencia",
            name="asistencias_trabaja_22d0c7_idx",
        ),
        migrations.RemoveIndex(
            model_name="asistencia",
            name="asistencias_fecha_3831c0_idx",
        ),
        migrations.RemoveIndex(
            model_name="resumendiario",
            name="asistencias_fecha_d69d91_idx",
        ),
        migrations.RemoveIndex(
            model_name="resumendiario",
            name="asistencias_trabaja_4fc997_idx",
        ),
        migrations.AlterUniqueTogether(
            name="asistencia",
            unique_together={("trabajador", "fecha")},
        ),
        migrations.RemoveField(
            model_name="resumendiario",
            name="creado_en",
        ),
        migrations.RemoveField(
            model_name="resumendiario",
            name="hora_entrada",
        ),
        migrations.RemoveField(
            model_name="resumendiario",
            name="hora_salida",
        ),
        migrations.RemoveField(
            model_name="resumendiario",
            name="horas_normales",
        ),
        migrations.RemoveField(
            model_name="resumendiario",
            name="modificado_en",
        ),
        migrations.RemoveField(
            model_name="resumendiario",
            name="salio_temprano",
        ),
        migrations.AlterField(
            model_name="asistencia",
            name="creado_en",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Creado En"),
        ),
        migrations.AlterField(
            model_name="asistencia",
            name="dispositivo_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID del Dispositivo"
            ),
        ),
        migrations.AlterField(
            model_name="asistencia",
            name="distancia_entrada",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Distancia Entrada (metros)",
            ),
        ),
        migrations.AlterField(
            model_name="asistencia",
            name="estado",
            field=models.CharField(
                choices=[
                    ("abierto", "Turno Abierto"),
                    ("cerrado", "Turno Cerrado"),
                    ("editado", "Editado Manualmente"),
                    ("sincronizado", "Sincronizado con App"),
                ],
                default="abierto",
                max_length=20,
                verbose_name="Estado",
            ),
        ),
        migrations.AlterField(
            model_name="asistencia",
            name="fecha",
            field=models.DateField(
                default=django.utils.timezone.now, verbose_name="Fecha"
            ),
        ),
        migrations.AlterField(
            model_name="asistencia",
            name="hora_entrada",
            field=models.TimeField(default="00:00:00", verbose_name="Hora de Entrada"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="asistencia",
            name="llego_tarde",
            field=models.BooleanField(default=False, verbose_name="Llegó Tarde"),
        ),
        migrations.AlterField(
            model_name="asistencia",
            name="metodo_identificacion",
            field=models.CharField(
                choices=[
                    ("qr", "Código QR"),
                    ("cedula", "Cédula Física"),
                    ("manual", "Registro Manual"),
                ],
                default="manual",
                max_length=20,
                verbose_name="Método de Identificación",
            ),
        ),
        migrations.AlterField(
            model_name="asistencia",
            name="modificado_en",
            field=models.DateTimeField(auto_now=True, verbose_name="Modificado En"),
        ),
        migrations.AlterField(
            model_name="asistencia",
            name="puesto_laboral",
            field=models.CharField(max_length=100, verbose_name="Puesto Laboral"),
        ),
        migrations.AlterField(
            model_name="asistencia",
            name="registrado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="asistencias_registradas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Registrado Por",
            ),
        ),
        migrations.AlterField(
            model_name="asistencia",
            name="salio_temprano",
            field=models.BooleanField(default=False, verbose_name="Salió Temprano"),
        ),
        migrations.AlterField(
            model_name="asistencia",
            name="sincronizado_en",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Sincronizado En"
            ),
        ),
        migrations.AlterField(
            model_name="asistencia",
            name="ubicacion_entrada_valida",
            field=models.BooleanField(
                default=True, verbose_name="Ubicación de Entrada Válida"
            ),
        ),
        migrations.AlterField(
            model_name="asistencia",
            name="ubicacion_salida_valida",
            field=models.BooleanField(
                default=True, verbose_name="Ubicación de Salida Válida"
            ),
        ),
        migrations.AlterField(
            model_name="resumendiario",
            name="asistio",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="resumendiario",
            name="fecha",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="resumendiario",
            name="horas_extras",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="resumendiario",
            name="horas_totales",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name="resumendiario",
            name="llego_tarde",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="resumendiario",
            name="observaciones",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="resumendiario",
            name="proyecto",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resumenes_diarios",
                to="proyectos.proyecto",
            ),
        ),
        migrations.AlterField(
            model_name="resumendiario",
            name="trabajador",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="resumenes_diarios",
                to="trabajadores.trabajador",
            ),
        ),
        migrations.AddIndex(
            model_name="asistencia",
            index=models.Index(
                fields=["fecha", "trabajador"], name="asistencias_fecha_a6c89e_idx"
            ),
        ),
        migrations.AlterModelTable(
            name="resumendiario",
            table="resumen_diario",
        ),
        migrations.RemoveField(
            model_name="asistencia",
            name="salario_dia",
        ),
        migrations.RemoveField(
            model_name="asistencia",
            name="tarifa_hora_extra",
        ),
    ]
