# Generated by Django 5.2.7 on 2025-11-02 23:28

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "asistencias",
            "0002_remove_asistencia_asistencias_trabaja_22d0c7_idx_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="asistencia",
            name="es_dia_festivo",
            field=models.BooleanField(
                default=False,
                help_text="Indica si este día es festivo",
                verbose_name="Es Día Festivo",
            ),
        ),
        migrations.AddField(
            model_name="asistencia",
            name="horas_festivas",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Horas trabajadas en día festivo",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Horas en Festivo",
            ),
        ),
        migrations.AddField(
            model_name="asistencia",
            name="horas_nocturnas",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Horas trabajadas entre 6pm y 6am",
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Horas Nocturnas",
            ),
        ),
        migrations.AddField(
            model_name="asistencia",
            name="salario_dia",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Salario normal del trabajador este día",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Salario del Día",
            ),
        ),
        migrations.AddField(
            model_name="asistencia",
            name="salario_hora_festiva",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Tarifa especial por hora en festivo",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Tarifa Hora Festiva",
            ),
        ),
        migrations.AddField(
            model_name="asistencia",
            name="salario_hora_nocturna",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Tarifa especial por hora nocturna",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Tarifa Hora Nocturna",
            ),
        ),
        migrations.AddField(
            model_name="asistencia",
            name="tarifa_hora_extra",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Tarifa por hora extra este día",
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                verbose_name="Tarifa Hora Extra",
            ),
        ),
    ]
