# Generated by Django 5.2.7 on 2025-11-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "asistencias",
            "0003_asistencia_es_dia_festivo_asistencia_horas_festivas_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="asistencia",
            name="minutos_tarde",
            field=models.IntegerField(default=0, help_text="Minutos de tardanza"),
        ),
    ]
