# Generated by Django 5.2.7 on 2025-11-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistencias", "0004_asistencia_minutos_tarde"),
    ]

    operations = [
        migrations.AddField(
            model_name="asistencia",
            name="eliminado",
            field=models.BooleanField(default=False, verbose_name="Eliminado"),
        ),
    ]
