# Generated by Django 5.2.7 on 2025-11-11 04:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistencias", "0005_asistencia_eliminado"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="asistencia",
            name="corregida_fecha",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Corrección"
            ),
        ),
        migrations.AddField(
            model_name="asistencia",
            name="corregida_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="asistencias_corregidas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Corregida Por",
            ),
        ),
        migrations.AddField(
            model_name="asistencia",
            name="fue_corregida",
            field=models.BooleanField(
                default=False,
                help_text="Indica si esta asistencia fue corregida por un supervisor",
                verbose_name="Fue Corregida",
            ),
        ),
        migrations.AddField(
            model_name="asistencia",
            name="hora_entrada_original",
            field=models.TimeField(
                blank=True,
                help_text="Hora de entrada antes de la corrección",
                null=True,
                verbose_name="Hora Entrada Original",
            ),
        ),
        migrations.AddField(
            model_name="asistencia",
            name="hora_salida_original",
            field=models.TimeField(
                blank=True,
                help_text="Hora de salida antes de la corrección",
                null=True,
                verbose_name="Hora Salida Original",
            ),
        ),
        migrations.AddField(
            model_name="asistencia",
            name="motivo_correccion",
            field=models.TextField(
                blank=True,
                help_text="Explica por qué se corrigió la marcación",
                verbose_name="Motivo de Corrección",
            ),
        ),
        migrations.AddField(
            model_name="asistencia",
            name="observaciones_validacion",
            field=models.TextField(
                blank=True,
                help_text="Comentarios del supervisor al validar",
                verbose_name="Observaciones de Validación",
            ),
        ),
        migrations.AddField(
            model_name="asistencia",
            name="validado",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el supervisor validó esta asistencia",
                verbose_name="Validado",
            ),
        ),
        migrations.AddField(
            model_name="asistencia",
            name="validado_fecha",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Fecha de Validación"
            ),
        ),
        migrations.AddField(
            model_name="asistencia",
            name="validado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="asistencias_validadas",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Validado Por",
            ),
        ),
    ]
