# Generated by Django 5.2.7 on 2026-03-28 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "asistencias",
            "0006_asistencia_corregida_fecha_asistencia_corregida_por_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="asistencia",
            name="turnos",
            field=models.IntegerField(
                default=0,
                help_text="Cantidad de turnos para trabajadores por turno (guardas). 0 para trabajadores normales.",
                verbose_name="Turnos",
            ),
        ),
    ]
