# Generated by Django 5.2.7 on 2026-04-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("asistencias", "0007_asistencia_turnos"),
    ]

    operations = [
        migrations.AddField(
            model_name="asistencia",
            name="archivo_justificacion",
            field=models.FileField(
                blank=True,
                help_text="Foto o documento de soporte para la justificación",
                null=True,
                upload_to="asistencias/justificaciones/",
                verbose_name="Constancia de Justificación",
            ),
        ),
    ]
