# Generated by Django 5.2.7 on 2025-10-25 05:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Usuario",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        error_messages={
                            "unique": "Ya existe un usuario con este correo electrónico."
                        },
                        help_text="Correo electrónico para autenticación",
                        max_length=254,
                        unique=True,
                        verbose_name="Correo Electrónico",
                    ),
                ),
                (
                    "nombre_completo",
                    models.CharField(
                        help_text="Nombre completo del usuario",
                        max_length=255,
                        verbose_name="Nombre Completo",
                    ),
                ),
                (
                    "rol",
                    models.CharField(
                        choices=[
                            ("administrador", "Administrador"),
                            ("supervisor", "Supervisor"),
                            ("trabajador", "Trabajador"),
                        ],
                        default="trabajador",
                        help_text="Rol del usuario en el sistema",
                        max_length=20,
                        verbose_name="Rol",
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True,
                        help_text="Indica si el usuario puede acceder al sistema",
                        verbose_name="Activo",
                    ),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Fecha de Actualización"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Los grupos a los que pertenece este usuario.",
                        related_name="usuario_set",
                        related_query_name="usuario",
                        to="auth.group",
                        verbose_name="grupos",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Permisos específicos para este usuario.",
                        related_name="usuario_set",
                        related_query_name="usuario",
                        to="auth.permission",
                        verbose_name="permisos de usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usuario",
                "verbose_name_plural": "Usuarios",
                "db_table": "usuarios",
                "ordering": ["-fecha_creacion"],
            },
        ),
    ]
