# Generated by Django 5.2.7 on 2025-11-13 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.CharField(
                choices=[
                    ("administrador", "Administrador"),
                    ("gerente", "Gerente"),
                    ("contador", "Contador"),
                    ("residente", "Residente de Obra"),
                    ("supervisor", "Supervisor"),
                    ("trabajador", "Trabajador"),
                ],
                default="trabajador",
                help_text="Rol del usuario en el sistema",
                max_length=20,
                verbose_name="Rol",
            ),
        ),
    ]
