# Generated by Django 5.2.7 on 2026-02-18 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0003_rol_permite_auto_registro"),
        ("usuarios", "0003_sistema_roles"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usuario",
            name="rol",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="usuarios",
                to="admin_panel.rol",
                verbose_name="Rol",
            ),
        ),
    ]
