# Generated by Django 5.2.7 on 2026-03-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0004_alter_usuario_rol"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="foto",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="usuarios/fotos/",
                verbose_name="Foto de Perfil",
            ),
        ),
        migrations.AddField(
            model_name="usuario",
            name="telefono",
            field=models.CharField(
                blank=True, default="", max_length=20, verbose_name="Teléfono"
            ),
        ),
    ]
