# Generated by Django 5.2.7 on 2025-12-24 05:56

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConfiguracionEmpresa",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre_empresa",
                    models.CharField(
                        default="QUADYCONS",
                        max_length=200,
                        verbose_name="Nombre de la Empresa",
                    ),
                ),
                (
                    "logo_empresa",
                    models.ImageField(
                        blank=True,
                        help_text="Logo que aparecerá en todos los reportes (PNG, JPG o SVG)",
                        null=True,
                        upload_to="empresa/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg", "jpeg", "svg"]
                            )
                        ],
                        verbose_name="Logo de la Empresa",
                    ),
                ),
                (
                    "direccion",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Dirección"
                    ),
                ),
                (
                    "telefono",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Teléfono"
                    ),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=254, verbose_name="Email"),
                ),
                (
                    "ruc",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="RUC / RIF"
                    ),
                ),
                (
                    "tipo_cambio_default",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("36.60"),
                        help_text="Córdobas por cada Dólar (ej: 36.60)",
                        max_digits=10,
                        verbose_name="Tipo de Cambio por Defecto",
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Creación"
                    ),
                ),
                (
                    "fecha_actualizacion",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Última Actualización"
                    ),
                ),
            ],
            options={
                "verbose_name": "Configuración de Empresa",
                "verbose_name_plural": "Configuración de Empresa",
                "db_table": "configuracion_empresa",
            },
        ),
    ]
