# Generated by Django 5.2.7 on 2026-04-08 00:50

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reportes", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ReporteGastos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "codigo",
                    models.CharField(
                        help_text="Se genera automáticamente",
                        max_length=20,
                        unique=True,
                        verbose_name="Código",
                    ),
                ),
                ("periodo_inicio", models.DateField(verbose_name="Período Inicio")),
                ("periodo_fin", models.DateField(verbose_name="Período Fin")),
                (
                    "tipo_cambio",
                    models.DecimalField(
                        decimal_places=4,
                        default=Decimal("36.6000"),
                        max_digits=10,
                        verbose_name="Tipo de Cambio (C$/USD)",
                    ),
                ),
                (
                    "estado",
                    models.CharField(
                        choices=[
                            ("borrador", "Borrador"),
                            ("aprobada_gerente", "Aprobada por Gerente"),
                            ("aprobada_contador", "Aprobada por Contador"),
                            ("pagada", "Pagada"),
                            ("anulada", "Anulada"),
                        ],
                        default="borrador",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "total_cordobas",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total Córdobas",
                    ),
                ),
                (
                    "total_dolares",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Total Dólares",
                    ),
                ),
                (
                    "fecha_aprobacion_gerente",
                    models.DateTimeField(blank=True, null=True),
                ),
                (
                    "fecha_aprobacion_contador",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("fecha_pago", models.DateTimeField(blank=True, null=True)),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                (
                    "eliminado",
                    models.BooleanField(default=False, verbose_name="Eliminado"),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("modificado_en", models.DateTimeField(auto_now=True)),
                (
                    "aprobada_contador_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reportes_gastos_aprobados_contador",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobada Contador Por",
                    ),
                ),
                (
                    "aprobada_gerente_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reportes_gastos_aprobados_gerente",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Aprobada Gerente Por",
                    ),
                ),
                (
                    "generado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reportes_gastos_generados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Generado Por",
                    ),
                ),
                (
                    "pagada_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reportes_gastos_pagados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Pagada Por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Reporte de Gastos",
                "verbose_name_plural": "Reportes de Gastos",
                "db_table": "reportes_gastos",
                "ordering": ["-creado_en"],
            },
        ),
        migrations.CreateModel(
            name="DetalleReporteGastos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_item", models.IntegerField(verbose_name="N°")),
                (
                    "concepto",
                    models.CharField(
                        help_text="Ej: INSS, INATEC, Combustible, Transporte, etc.",
                        max_length=500,
                        verbose_name="Concepto",
                    ),
                ),
                (
                    "monto_cordobas",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Monto Córdobas",
                    ),
                ),
                (
                    "monto_dolares",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        verbose_name="Monto Dólares",
                    ),
                ),
                (
                    "archivo_soporte",
                    models.FileField(
                        blank=True,
                        help_text="Factura o recibo de soporte",
                        max_length=500,
                        null=True,
                        upload_to="reportes/gastos/soportes/",
                        verbose_name="Archivo Soporte",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(blank=True, verbose_name="Observaciones"),
                ),
                ("creado_en", models.DateTimeField(auto_now_add=True)),
                ("modificado_en", models.DateTimeField(auto_now=True)),
                (
                    "creado_por",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado Por",
                    ),
                ),
                (
                    "reporte",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="detalles",
                        to="reportes.reportegastos",
                        verbose_name="Reporte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Detalle de Gasto",
                "verbose_name_plural": "Detalles de Gastos",
                "db_table": "detalles_reporte_gastos",
                "ordering": ["numero_item"],
            },
        ),
    ]
