# Generated by Django 5.2.7 on 2026-02-17 02:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Rol",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nombre",
                    models.CharField(max_length=50, unique=True, verbose_name="Nombre"),
                ),
                (
                    "descripcion",
                    models.TextField(blank=True, verbose_name="Descripción"),
                ),
                (
                    "codigo",
                    models.SlugField(max_length=30, unique=True, verbose_name="Código"),
                ),
                (
                    "es_sistema",
                    models.BooleanField(
                        default=False, verbose_name="Es rol del sistema"
                    ),
                ),
                ("activo", models.BooleanField(default=True, verbose_name="Activo")),
                ("permisos", models.JSONField(default=dict, verbose_name="Permisos")),
                (
                    "alcance_proyectos",
                    models.CharField(
                        choices=[
                            ("todos", "Todos los proyectos"),
                            ("asignados", "Solo proyectos asignados"),
                            ("propio", "Solo proyecto propio"),
                            ("ninguno", "Sin acceso a proyectos"),
                        ],
                        default="asignados",
                        max_length=20,
                        verbose_name="Alcance de proyectos",
                    ),
                ),
                (
                    "solo_app_movil",
                    models.BooleanField(default=False, verbose_name="Solo app móvil"),
                ),
                (
                    "fecha_creacion",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de creación"
                    ),
                ),
                (
                    "creado_por",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="roles_creados",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Creado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rol",
                "verbose_name_plural": "Roles",
                "db_table": "roles",
                "ordering": ["nombre"],
            },
        ),
    ]
