# Generated by Django 5.2.7 on 2026-02-18 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admin_panel", "0002_crear_roles_predefinidos"),
    ]

    operations = [
        migrations.AddField(
            model_name="rol",
            name="permite_auto_registro",
            field=models.BooleanField(
                default=False,
                help_text="Si está activo, este rol aparecerá como opción en el formulario de registro público",
                verbose_name="Permitir auto-registro",
            ),
        ),
    ]
